### ISSUE TITLE
菇凉，你太狠了，把所有node_module传来了……

### ISSUE THREAD

**Issue by kvkens** [SimplyWenjing/ES6#1]
我只求看一下package.json就好了，这太狠了~~~

**Comment by SimplyWenjing** [comment]
我把package.json刚传上来，能不能麻烦帮忙看看，为什么我只安装了package.json里的那些依赖，可是我的node_modules里面却多出来了那么多文件夹呀~~~求解答

**Comment by kvkens** [comment]
是不是你用了cnpm进行安装的？

**Comment by SimplyWenjing** [comment]
我的命令都是使的npm啊啊啊，我同学跟我用一样的命令，安装的就是package.json里的那些依赖，可我就是那么多文件 T^T   Ps. I love Jay Chou！>.<

**Comment by kvkens** [comment]
love Jay too~~~  我之前用过cnpm会产生很多平铺在node_modules 里面，我看了下我的webpack，也没有那么多余的，都是在package里面依赖可看到的，实在不行就stackoverflow试试 吧~ 或者去cnodejs社区问问咯。

**Comment by kvkens** [comment]
我知道是怎么回事了，今天更新了node.js 4.5版本，从4.2开始node_modules目录就不会无限依赖进去了，都是平铺在根目录里面了，这样不会重复下载。

**Comment by SimplyWenjing** [comment]
这样啊，那我也更新一下node.js~~~多谢！
