### ISSUE TITLE
为什么我只安装了package.json里面的依赖，可node_modules里面却多出来了那么多文件夹

### ISSUE THREAD

**Issue by SimplyWenjing** [SimplyWenjing/ES6#2]
如题

**Comment by firesky594** [comment]
因为npm install 的时候会将 Dependencies里面的依赖包下载下来,webpack打包的时候调用.

**Comment by SimplyWenjing** [comment]
可是我的package.json里面只写了几个依赖包，为啥下载了那么多不知道是啥的文件呢T^T

**Comment by firesky594** [comment]
一个依赖包会依赖另外一个依赖包,如果你写的依赖包需要其他的依赖包的话,它会自动帮你下载其他依赖包先的.

2016-08-11 21:32 GMT+08:00 季诗筱 notifications@github.com:
